# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  show-vscode-versions:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: show available vscode versions
        run: bash ./show-vscode-versions.bash

  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: build the container
        working-directory: ./docker
        run: docker build -t vscode .
